export const STRING = {
  COMMON: {
    PRODUCTION: "Under Production...",
    BACK: "BACK",
  },
  START: {
    LEARN: "Learn your instrument from anywhere with MUSIC AI",
    STARTED: "GET STARTED",
  },
  LOGIN: {
    HEY: "Hey there!",
    WELCOME: "Welcome back",
    LOGIN: "Email",
    PASSWORD: "Password",
    REMEMBER: "Remember me",
    SIGNUP: "SIGN UP",
    SIGNIN: "SIGN IN",
  },
  REGISTER: {
    CREATE: "Create new account",
    SET_PHOTO: "Set Profile Photo",
    FIRSTNAME:"Firstname",
    LASTNAME:"Lastname",
    EMAIL: "Email",
    PASSWORD: "Password",
    MOBILE:"Mobile",
    INSTRUMENT: "How well do you know your instrument?",
    MEMBERSHIP: "MEMBERSHIP",
    ABOUT_US: "How do you know about us?",
    CREATE_ACC: "CREATE ACCOUNT",
  },
  HOME: {
    HEY: "Hey  ",
    USER: "Savani!",
    PLAY_TODAY: "What do you want to play today ?",
    LIBRARY: "Library",
    SIGHT_READ: "Sight Read",
    ADD_MUSIC: "Add Music",
  },
  TAB: {
    HOME: "Home",
    TUNER: "Tuner",
    METRONOME: "Metronome",
    PROFILE: "Profile",
  },
  ACCOUNT: {
    NAME: "Name",
    EMAILL: "Email",
    SET_ACC: "SET ACCOUNT",
  },

  PROFILE: {
    YOUR_PROFILE: "Your profile",
    NAME: "Name:",
    EMAIL: "Email:",
    PHONE: "Phone:",
    HELP: "HELP",
    UPDATE:"UPDATE",
    LOGOUT:"LOGOUT"
  },
  MEMBERSHIP: {
    SUBSCRIPTION: "Subscription",
    PAYMENT: "Payment",
    SUBSCRIBE: "SUBSCRIBE",
  },
  KNOW_ABOUT: {
    KNOW_ABOUT: "How do you know about us",
    APP_STORE: "App store Search",
    GOOGLE: "Google",
    FACEBOOK: "Facebook",
  },
  KNOW_INSTRUMENT: {
    YOUR_INSTRUMENT: "How well do you know your instrument",
  },
  TUNER: {
    TUNER: "Tuner",
    GOT_IT: "Got It",
    CHROMATIC: "Chromatic Tunning",
    TONE_GENERATOR: "Tone Generator",
    PINCH: "A4",
    FLAT: "♭",
    SHARP: "#",
  },
  METRONOME: {
    METRONOME: "Metronome",
    PENDULUM: "Metronome Pendulum",
    MINUS: "-",
    CROTCHET: "♩ =",
    120: "120",
    BPM: "BPM",
    PLUS: "+",
    ADAGIO: "Adagio",
    TAP: "TAP",
    DIVIDE: "4/4",
    CROTCHET1: "♩",
  },
  LIBRARY: {
    TITLE: "Library",
    COMPOSER: "Composer",
    GENRES: "Genres",
    CLOUD: "Cloud",
  },
  CLOUD: {
    SCAN: "Scan",
    IMPORT: "Import",
    EXCERPT: "Excerpt",
  },
  COMPOSERLIBRARY: {
    TITLE: "Composer Library",
    SEARCH: "Search",
    LESSION: "Lession",
    ARTIST: "Artist",
    GENRES: "Genres",
  },
  GENRESLIBRARY: {
    TITLE: "Genres Library",
    SEARCH: "Search",
    LESSION: "Lession",
    ARTIST: "Artist",
    GENRES: "Genres",
  },
  PERFORM: {
    TAKE: "Take 1",
    RECORD: "RECORD",
    DELETE: "DELETE",
  },
  PERFORM2: {
    RECORD: "RECORD",
  },
  COMPARE: {
    TITLE: "Compare",
    INT: "INT",
    DYNAMIC: "DYNAMIC",
    TEMP: "TEMP",
    PRACTICE: "PRACTICE",
  },
  COMPOSERLIBRARY: {
    TITLE: "Composer Library",
    SEARCH: "Search",
    LESSION: "Lession",
    ARTIST: "Artist",
    GENRES: "Genres",
  },
  SOLOLIBRARY: {
    TITLE: "Solo Library",
    SEARCH: "Search",
  },
  ADDMUSIC: {
    SCAN: "Scan Now",
    IMPORT: "Import Now",
    RECENTS: "Recents",
    TITLENAME: "Title",
    TITLE: "Add Music",
    ARTIST: "Artist",
    GENRES: "Genres",
    NEW: "New",
  },
  PREV_EXPERT: {
    TITLE: "Last Music Played",
    SUBTITLE: "Previous Music Played",
  },
  SIGHT_READ: {
    HEADER: "Sight Read",
    TITLE: "Previous Excerpt",
    VIEW: "VIEW ALL",
    SUB_TITLE: "Today's Excerpt",
    PLAY: "PLAY",
  },
  RECORDING: {
    BACK: "BACK",
    RECORDING: "Recording 1",
    SCORE: "Performance Score",
    REDO: "RE-DO",
    REVIEW: "REVIEWING",
  },
  SCAN: {
    SCAN: "Scan",
    DOC_NAME: "Name your document",
    TITLE: "Title",
    ARTIST: "Artist",
    ADD: "ADD TO LIBRARY",
  },
  IMPORT: {
    TITLE: "Import",
    ARTIST: "Artist",
    ADD: "ADD TO LIBRARY",
  },
  TUNE_SETTING: {
    TITLE: "Tune Settings",
  },
  METRO_SETTING: {
    TITLE: "Metronome Setting",
    TIME: "time signature:",
    BEAT: "beat type:",
    PENDULUM: "pendulum metronome",
    SAVE: "SAVE",
  },
  RECORD: {
    RECORD: "RECORD",
    STOP: "STOP",
  },
};
